
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOMAIN SCHEMA TLDurl : SCHEMA DOMAIN secondaryDomains TLDsecondaryDomains : DOMAIN secondaryDomains\n                        | emptyempty : '
    
_lr_action_items = {'SCHEMA':([0,],[1,]),'DOMAIN':([1,3,6,],[3,6,6,]),'$end':([2,7,],[0,-1,]),'TLD':([3,4,5,6,8,],[-4,7,-3,-4,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'secondaryDomains':([3,6,],[4,8,]),'empty':([3,6,],[5,5,]),'url':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> url","S'",1,None,None,None),
  ('url -> SCHEMA DOMAIN secondaryDomains TLD','url',4,'p_url','FTPYacc.py',6),
  ('secondaryDomains -> DOMAIN secondaryDomains','secondaryDomains',2,'p_secondaryDomains','FTPYacc.py',15),
  ('secondaryDomains -> empty','secondaryDomains',1,'p_secondaryDomains','FTPYacc.py',16),
  ('empty -> <empty>','empty',0,'p_empty','FTPYacc.py',25),
]
